export const ActionTypes={
    ADD_QUESTION:"ADD_QUESTION",
    WRONG_QUESTION:"WRONG_QUESTION",
    REMOVE_WRONG_QUESTION:"REMOVE_WRONG_QUESTION",
    REMOVEALL_WRONG_QUESTION:"REMOVEALL_WRONG_QUESTION",
    IS_SUBMITED:"IS_SUBMITED"
};